const { Schema, model, models } = require("mongoose");

const clientSchema = new Schema(
  {
    appId: { type: String, required: true, unique: true, index: true },
    name: { type: String, required: true, trim: true },
    industry: { type: String, required: true, trim: true },
    plan: { type: String, required: true },
    monthlyCredits: { type: Number, default: 2000 },
    purchasedCredits: { type: Number, default: 0 },
    usedCredits: { type: Number, default: 0 },
    totalCredits: { type: Number, default: 2000 },
    billingCycle: { type: String, default: "monthly" },
    creditTransactions: { type: [Schema.Types.Mixed], default: [] },
    status: { type: String, required: true },
    domain: { type: String, default: "" },
    domainStatus: { type: String, default: "not_configured" },
    subdomain: { type: String, required: true, trim: true, unique: true },
    activeUsers: { type: Number, default: 0 },
    trainings: { type: Number, default: 0 },
    sessions: { type: Number, default: 0 },

    // Feature Set 6 / Task 2: lifetime quota model (additive, backward-compatible).
    // Effective limit = base + purchased (purchased filled by Task-4 add-ons).
    // Lifetime usage is permanent (consumed on publish/create, never refunded on
    // delete). base `null` = unlimited (enterprise). `quotaInitialized` marks that
    // the one-time backfill from plan + current counts has run for this client.
    trainingBaseLimit: { type: Number, default: null },
    trainingPurchasedLimit: { type: Number, default: 0 },
    trainingUsedLifetime: { type: Number, default: 0 },
    sessionBaseLimit: { type: Number, default: null },
    sessionPurchasedLimit: { type: Number, default: 0 },
    sessionUsedLifetime: { type: Number, default: 0 },
    userBaseLimit: { type: Number, default: null },
    userPurchasedLimit: { type: Number, default: 0 },
    userUsedLifetime: { type: Number, default: 0 },
    quotaInitialized: { type: Boolean, default: false },
    // Phase C: entitlement snapshot frozen at purchase/upgrade (R3). Future plan
    // edits never overwrite these — existing subscribers keep what they bought.
    subscribedPlan: { type: String, default: "" },
    creditBaseLimit: { type: Number, default: null },
    entitlementSnapshotAt: { type: Date, default: null },
    // Issue 1: subscription expiry. Stamped on plan assign/purchase/renewal.
    // Once `now` passes this date the subscription is expired regardless of
    // remaining credits. null on legacy clients → expiry is computed from the
    // plan start (see getSubscriptionExpiry) for backward compatibility.
    planExpiryDate: { type: Date, default: null },
    joined: { type: String, default: "" },
    csm: { type: String, required: true, trim: true },
    logo: { type: String, default: "" },
    logoColor: { type: String, default: "#3e60d5" },
    logoBg: { type: String, default: "#ebf2ff" },
    iframeEnabled: { type: Boolean, default: true },
    ssoType: { type: String, default: "None" },
    ssoStatus: { type: String, default: "not_configured" },
    primaryColor: { type: String, default: "#1428a0" },
    secondaryColor: { type: String, default: "#3e60d5" },
    supportEmail: { type: String, default: "" },
    companyPhone: { type: String, default: "" },
    companyAddress: { type: String, default: "" },
    applicationName: { type: String, default: "" },
    logoUrl: { type: String, default: "" },
    darkLogoUrl: { type: String, default: "" },
    faviconUrl: { type: String, default: "" },
    allowedOrigins: { type: [String], default: [] },
    webhookUrl: { type: String, default: "" },
    webhookSigningSecret: { type: String, default: "" },
    lastWebhookTestAt: { type: String, default: "" },
    lastWebhookTestStatus: { type: String, default: "not_tested" },
    lastWebhookTestMessage: { type: String, default: "" },
    apiScope: { type: String, default: "" },
    iframeBaseUrl: { type: String, default: "" },
    iframeAllowedParentDomains: { type: [String], default: [] },
    emailDeliveryEnabled: { type: Boolean, default: false },
    smtpHost: { type: String, default: "" },
    smtpPort: { type: Number, default: 587 },
    smtpUsername: { type: String, default: "" },
    smtpPassword: { type: String, default: "" },
    smtpFromName: { type: String, default: "" },
    smtpFromEmail: { type: String, default: "" },
    smtpSecure: { type: Boolean, default: false },
    smtpTestRecipient: { type: String, default: "" },
    lastSmtpTestAt: { type: String, default: "" },
    lastSmtpTestStatus: { type: String, default: "not_tested" },
    lastSmtpTestMessage: { type: String, default: "" },
    smtpTrainingAssignmentSubject: { type: String, default: "" },
    smtpTrainingAssignmentTemplate: { type: String, default: "" },
    emailSetPasswordSubject: { type: String, default: "" },
    emailSetPasswordTemplate: { type: String, default: "" },
    emailResetPasswordSubject: { type: String, default: "" },
    emailResetPasswordTemplate: { type: String, default: "" },
    emailSignatureHtml: { type: String, default: "" },
    emailSignatureImageUrl: { type: String, default: "" },
    domainVerificationToken: { type: String, default: "" },
    domainVerificationHost: { type: String, default: "_trainup-verification" },
    domainLastCheckedAt: { type: String, default: "" },
    domainLastCheckedResult: { type: String, default: "" },
    domainVerifiedAt: { type: String, default: "" },
    paymentProvider: { type: String, default: "razorpay" },
    paymentMode: { type: String, default: "test" },
    billingCurrency: { type: String, default: "INR" },
    razorpayKeyId: { type: String, default: "" },
    razorpayKeySecret: { type: String, default: "" },
    enterpriseMonthlyPrice: { type: Number, default: 0 },
    enterpriseMonthlyCredits: { type: Number, default: 0 },
    enterpriseSupportNotes: { type: String, default: "" },
    enterpriseRequests: { type: [Schema.Types.Mixed], default: [] },
    ssoProviderType: { type: String, default: "none" },
    ssoClientId: { type: String, default: "" },
    ssoClientSecret: { type: String, default: "" },
    ssoTenantId: { type: String, default: "" },
    ssoIssuerUrl: { type: String, default: "" },
    ssoEntryPoint: { type: String, default: "" },
    ssoAudience: { type: String, default: "" },
    ssoRedirectUri: { type: String, default: "" },
    ssoButtonLabel: { type: String, default: "" },
    ssoAllowedDomains: { type: [String], default: [] },
    ssoAutoProvisionUsers: { type: Boolean, default: true },
    clientAdminUserId: { type: String, default: "" },
    firstUserName: { type: String, default: "" },
    firstUserEmail: { type: String, default: "" },
    // LMS Integration (LMS_INTEGRATION_RESEARCH.md)
    ltiClientId: { type: String, default: "" },
    ltiDeploymentId: { type: String, default: "" },
    ltiPlatformKeysetUrl: { type: String, default: "" },
    ltiAccessTokenUrl: { type: String, default: "" },
    ltiOidcAuthUrl: { type: String, default: "" },
    scormEnabled: { type: Boolean, default: true },
    xapiEnabled: { type: Boolean, default: false },
    xapiLrsEndpoint: { type: String, default: "" },
    xapiClientId: { type: String, default: "" },
    xapiClientSecret: { type: String, default: "" },
  },
  {
    timestamps: true,
  },
);

clientSchema.index({ status: 1, plan: 1 });
clientSchema.index({ name: 1 });

module.exports = models.Client || model("Client", clientSchema);
